name: Selenium with C#
on: push
jobs:
  job1:
    name: Selenium with C#
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "This test runs on ${{runner.os}}"
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - run: echo "This repo is ${{github.repository}}..."
