name: Selenium with C#
on: push
jobs:
  job1:
    name: Selenium with C#
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "This test runs on ${{runner.os}}"
      - name: Check out source code
        uses: actions/checkout@2.4.1
      - run: echo "This repo is ${{github.repository}}..."
